site_name: NNS Session Docs
site_url: https://samrosati.github.io/nns-session-documentation/
theme:
  name: material
  logo: assets/NNSsessionLogoDarkMode.png
  favicon: assets/NNSIconDarkOutline.png
  palette:
    # Dark Mode
    - scheme: slate
      toggle:
        icon: octicons/sun-16
        name: Dark mode
      primary: indigo
      accent: deep purple

    # Light Mode
    - scheme: default
      toggle:
        icon: octicons/moon-16
        name: Light mode
      primary: blue
      accent: deep orange

nav:
  - Home: index.md
  - Project Overview:
      - Project Proposal: 1_Project_Overview/1_1_Project_Proposal.md
      - Background & Context: 1_Project_Overview/1_2_Background_&_Context.md
  - Product Strategy & Discovery:
      - Market Analysis: 2_Product_Strategy_&_Discovery/2_1_Market_Analysis.md
      - User Personas: 2_Product_Strategy_&_Discovery/2_2_User_Personas.md
  - System Architecture:
      - High-Level Design: 3_System_Architecture/3_1_High-Level_Design.md
      - Codebase Structure & Optimization: 3_System_Architecture/3_2_Codebase_Structure_&_Optimization.md
      - Database Schema: 3_System_Architecture/3_3_Database_Schema.md
      - Native Strategy: 3_System_Architecture/3_4_Native_Strategy.md
  - Feature Deep Dives:
      - Skill Rating System: 4_Feature_Deep_Dives/4_1_Skill_Rating_System.md
      - Tournament Wizard: 4_Feature_Deep_Dives/4_2_Tournament_Wizard.md
      - Follower & Social System: 4_Feature_Deep_Dives/4_3_Follower_&_Social_System.md
      - Clinics: 4_Feature_Deep_Dives/4_4_Clinics.md
      - Tournaments: 4_Feature_Deep_Dives/4_5_Tournaments.md
      - Sessions: 4_Feature_Deep_Dives/4_6_Sessions.md
      - Messaging System: 4_Feature_Deep_Dives/4_7_Messaging_System.md
  - Dev Log:
      - Jan 2026: 5_Change_Logs/5_1_Jan_2026.md
  - AI Strategy: 6_AI_Strategy/6_1_AI_Strategy.md

markdown_extensions:
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
